replaced old logo with new logo, updated css properties
Curio-org/Curio pull request #51
Opened 2023-10-10 19:59 UTC by sdthaker

## Changes Made
* Removed width for logo. Now uses default width.
* Removed left-right padding from the span text `Your Video Translator :)` to align it with the logo for both screen sizes.
* Removed the span tag with `Curio` text for both screen sizes.
* Linked correct logo source to the `<img>` tag in order to show the correct logo on the website

## Changes in action
### When screen size is >= 768px
<img width="2054" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/d414163c-87ca-4226-a8b4-fb804216bdcc">

### When screen size is < 768px
<img width="760" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/bbf86038-3cd3-4bae-ab38-53d365d3a14b">

## Issue
* Fixes issue #43 

## Additional Notes
Please let me know if you want something added/removed as part of this PR, eg. if you'd want me to add/remove padding, margin or width changes, etc. @arjxn-py

2023-10-10 20:11 UTC, sdthaker commented
## Update
With the commit [59ed1b7](https://github.com/Curio-org/Curio/pull/51/commits/59ed1b71cd92d643b8c274ecf8ab051b2969af31) the div that contains the logo and curio text looks like this for better visibility for smaller screen size:

<img width="757" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/a4a1093e-b1ad-4dfe-aa23-d2948f77aef6">

2023-10-11 22:23 UTC, arjxn-py reviewed
Thanks @sdthaker very nice work. Some comments below

2023-10-11 22:23 UTC, arjxn-py commented on src/components/Header/Header.tsx
> -            <span>CURIO</span>
It would be nicer to have a span like before and just the **old logo** plus the **C of CURIO** to be replaced by the new logo.
Preferably [Csmall](https://github.com/Curio-org/Curio/blob/main/src/components/assets/images/Csmall.png) to keep it optimized.

2023-10-11 22:23 UTC, arjxn-py commented on src/components/Header/Header.tsx
> -            <span>CURIO</span>
Ditto.
Sorry to bother you with this.
Your solution was very nice 💯

2023-10-11 22:26 UTC, arjxn-py commented
Please make sure to synchronize your working branch before as I've added those logos in #54

2023-10-11 23:19 UTC, sdthaker commented
Added the requested changes in commit [706779a](https://github.com/Curio-org/Curio/pull/51/commits/706779acc39e468f403fa9be0a794e6bcdfdb0cd)

## <768 screen size:
<img width="1030" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/6fa47cd3-7adb-4155-827d-59cea77f7209">

## >= 768 screen size:
<img width="1028" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/b31174ad-6601-40d9-86e7-01ce0513d1b4">

2023-10-12 12:07 UTC, arjxn-py requested changes
Nice work @sdthaker 🙂, some suggestions below.

2023-10-12 12:07 UTC, arjxn-py commented on src/components/Header/header.css
>    height: 15mm;
```suggestion
  height: 12.5mm;
```

2023-10-12 12:07 UTC, arjxn-py commented on src/components/Header/header.css
>  }
```suggestion
  margin-bottom: 0.6rem;
}
```

2023-10-12 12:16 UTC, arjxn-py approved these changes

2023-10-12 12:17 UTC, merged