Add Navigation Functionality to Curio Logo
Curio-org/Curio pull request #67
Opened 2023-10-15 22:22 UTC by mnajibi

Changes implemented:
- Wrapped the Curio logo in `HeaderCurio` with the React Router's `Link` component.
- Ensured the logo acts as a link directing users to the homepage.

2023-10-15 23:59 UTC, arjxn-py commented
Thanks @mnajibi, thanks for opening this PR.
Before I review the changes I can see some conflicts in the `Header` component.
Let me know if you need help with that.

2023-10-16 02:16 UTC, mnajibi commented
Hi @arjxn-py , thanks for quick response. I've taken care of the conflicts in the Header component, and everything should be resolved now. Please feel free to review the changes whenever you're ready. 

Looking forward to your feedback!

2023-10-16 09:56 UTC, arjxn-py requested changes
Thanks @mnajibi, very nice work.
We use `""` instead of `''` to wrap classNames & modules.
Can you please look into that? Otherwise looks awesome.
Some suggestions below -

2023-10-16 09:56 UTC, arjxn-py commented on src/components/Header/Header.tsx
> +import { Link ,BrowserRouter as Router, Route, Switch } from 'react-router-dom';
```suggestion
import { Link ,BrowserRouter as Router } from 'react-router-dom';
```

Route & Switch are imported but not used.

2023-10-16 09:56 UTC, arjxn-py commented on src/components/Header/Header.tsx
> +          <Link to='/'>
```suggestion
          <Link to="/" style={{ textDecoration: "none" }}>
```

Currently when you hover over the logo, it shows underline. We can use this to avoid that.

2023-10-17 16:01 UTC, mnajibi commented on src/components/Header/Header.tsx
> +          <Link to='/'>
Inline css added in commit [b1e65d5aae](https://github.com/Curio-org/Curio/pull/67/commits/b1e65d5aae9e07aceaa5602029c8e72898d2fc92)

2023-10-17 18:20 UTC, arjxn-py approved these changes
Thanks @mnajibi, looks awesome 💯

2023-10-17 18:20 UTC, merged